Repository googleapis/gcs-resumable-upload, pull requests merged in 2019-05, with the labels that each got.

#212 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#213 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#214 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#216 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
Labels: cla: yes

#217 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#218 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: cla: yes

#215 build: only pipe to codecov if tests run in Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#220 build: upgrade gts and other dependencies for 2.x release
  package.json
  src/cli.ts
  src/index.ts
  system-test/kitchen.ts
  test/test.ts
Labels: cla: yes

#222 chore: release 2.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#224 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#225 build: add configuration for automated doc deployemnt
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#226 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#227 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
