Repository googleapis/gcs-resumable-upload, pull requests merged in 2019-02, with the labels that each got.

#177 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#179 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#181 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#182 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#184 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#183 build: use linkinator for docs test
  package.json
Labels: cla: yes

#174 fix: replace request with gaxios
  README.md
  package.json
  src/index.ts
  system-test/kitchen.ts
  test/test.ts
Labels: :rotating_light:, cla: yes

#186 Release gcs-resumable-upload v1.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes
