Repository googleapis/gcs-resumable-upload, pull requests merged in 2020-05, with the labels that each got.

#346 chore: unpin version of gts
  package.json
Labels: automerge, cla: yes

#348 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#349 feat: allow user-specified protocol for options.apiEndpoint
  src/index.ts
  test/test.ts
Labels: cla: yes
