Repository googleapis/gcs-resumable-upload, pull requests merged in 2020-07, with the labels that each got.

#358 chore: update issue template and secret scripts
  .github/ISSUE_TEMPLATE/bug_report.md
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#361 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#360 build: add config .gitattributes
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#362 fix: typeo in nodejs .gitattribute
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#366 build: missing closing paren in publish script
  .kokoro/publish.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#365 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#370 chore: add config files for cloud-rad for node.js, delete Node 8 templates
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: partial

#369 build: add Node 8 tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes, context: none

#371 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#372 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#373 build: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: cla: yes, context: full

#374 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full
