Repository googleapis/gcs-resumable-upload, pull requests merged in 2021-05, with the labels that each got.

#416 fix: bypass auth when using emulator
  src/index.ts
  test/test.ts
Labels: api: storage, cla: yes

#417 build: add generated-files bot config
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: storage, cla: yes, context: full

#420 build: remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full

#423 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  owlbot.py
  synth.metadata
  synth.py
Labels: api: storage, cla: yes
