Repository googleapis/gcs-resumable-upload, pull requests merged in 2021-01, with the labels that each got.

#400 docs: Replace Apache license headers with MIT
  .gitignore
  .kokoro/docs.sh
  .kokoro/populate-secrets.sh
  .kokoro/release/docs-devsite.sh
  samples/quickstart.js
  samples/system-test/system.js
  src/cli.ts
  src/index.ts
  system-test/kitchen.ts
  system-test/util.ts
  test/test.ts
Labels: api: storage, cla: yes

#401 docs: nightly template run
  .kokoro/docs.sh
  .kokoro/populate-secrets.sh
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: api: storage, cla: yes, context: none

#402 refactor(nodejs): move build cop to flakybot
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: storage, automerge, cla: yes, context: full
